### ISSUE TITLE
Implement ec2 exponential back-off  for cluster-loader

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#10]
From old repo:

ekuric commented on Apr 5
Amazon API will reject to serve if api rate is overcome, 
necessary to implement this in all functions which interact with amazon api 
-> http://docs.aws.amazon.com/general/latest/gr/api-retries.html
@ofthecurerh

ofthecurerh commented on Apr 12
The boto3 library handles exponential backoff and retries, we just need to properly handle the exception.

Example snippet:

def create_volume(self, availability_zone, *_kwargs):
    try:
        volume = self.resource.create_volume(
            DryRun = False,
            AvailabilityZone = availability_zone,
            *_kwargs)
    except botocore.exceptions.ClientError as err:
        logging.warn('Unexpected Error: %s', err.response['Error']['Code'])
    else:
        return volume
@ekuric

ekuric commented on Apr 14
@ofthecurerh thx, I will check to add this to create/delete scripts involving boto3.
@ekuric

ekuric commented 28 days ago
I have this working in my tests , will create PR for this PR

**Comment by ekuric** [comment]
I will update cluster-loader to support dynamic storage provision for ec2 ebs storage type. Once this is done, and knowing that exponential back-off is already part of kubernetes code then we will not need this any more - ec2 exponential back-off is already in place

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
