### ISSUE TITLE
identify process match patterns for logging

### ISSUE THREAD

**Issue by jeremyeder** [openshift/svt#106]
@rflorenc can you please identify the logging processes (fluentd, elastic, whatever else) and add them to our collectd config file.  See this PR for an example:

https://github.com/openshift/svt/pull/104/commits/b6925066808667a9170144c894e6fa94d1dd11f6

**Comment by rflorenc** [comment]
@jeremyeder 

I don't have a machine with collectd where I can test this atm.
But I would say something like

ProcessMatch "fluentd"  "/usr/bin/ruby /usr/bin/fluentd"
ProcessMatch "elasticsearch"  "/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true"
ProcessMatch "kibana" "/usr/bin/node /usr/share/kibana/src/bin/kibana.js"

?

elastic's cmdline can change depending on the heap boundaries passed to the process but /bin/java alone is too generic.



These are the processes running inside the containers:

Elasticsearch
/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true

sh-4.2$ cat /proc/1/cmdline 
/bin/java-Xms256m-Xmx1g-Djava.awt.headless=true-XX:+UseParNewGC-XX:+UseConcMarkSweepGC-XX:CMSInitiatingOccupancyFraction=75-XX:+UseCMSInitiatingOc
cupancyOnly-XX:+HeapDumpOnOutOfMemoryError-XX:+DisableExplicitGC-Dfile.encoding=UTF-8-Des.path.home=/usr/share/java/elasticsearch-Des.config=/usr/
share/java/elasticsearch/config/elasticsearch.yml-Xms128M-Xmx4096m-Delasticsearch-Des.foreground=yes-Des.path.home=/usr/share/elasticsearch-cp/usr
/share/java/elasticsearch/plugins/openshift-elasticsearch-plugin/log4j-1.2.17.jar:/usr/share/elasticsearch/lib/elasticsearch-1.5.2.redhat-1.jar:/u
sr/share/java/lucene-core.jar:/usr/share/java/lucene-contrib/lib/*org.elasticsearch.bootstrap.Elasticsearchsh-4.2$

Fluentd
/usr/bin/ruby /usr/bin/fluentd

Kibana
/usr/bin/node /usr/share/kibana/src/bin/kibana.js

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
