### ISSUE TITLE
Cluster loader: storage support creates PVCs in default namespace

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#108]
Something may have changed in OCP since storage support was added to cluster_loader, but currently the tool creates the PVCs in the default namespaces.   

Adding a namespace to the pvc template and giving it the value of the current namespace where the pod is being created fixes the problem.   Preparing a PR for this.

/cc: @ekuric

**Comment by mffiedler** [comment]
ceph is ok, just needs to be added for EBS

**Comment by ekuric** [comment]
I propose that I just implement dynamic provision feature in cluster-loader for ec2/gluster/ceph - with dynamic provision, we will have all in place regarding creating volumes and tagging them
@mffiedler what you think?

**Comment by mffiedler** [comment]
+1 to implementing dynamic provisioning - that's the preferred mechanism in OpenShift now.   I would be happy to help with the implementation or any testing if needed.

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
