### ISSUE TITLE
Cluster loader:  EBS volume tagging is not working

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#109]
Specified a value for ebstagprefix in the cluster_loader yaml file, but the volumes which were created were not tagged in EBS.   Will investigate further.

/cc: @ekuric

**Comment by ekuric** [comment]
I propose that I just implement dynamic provision feature in cluster-loader for ec2/gluster/ceph - with dynamic provision, we will have all in place regarding creating volumes and tagging them 
@mffiedler what you think?

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
