### ISSUE TITLE
customer feedback on network test

### ISSUE THREAD

**Issue by jeremyeder** [openshift/svt#116]
Comments from customer using the svt/networking tests:

I also tried to run Jeremy’s network benchmarck (svt), but we faced some difficulties:

- uperf  is automatically packaged inside docker images by the ansible playbook, but the docker images are built on the nodes themselves. And it failed because, on our R-Box setup, the nodes don’t have access to Internet.    So, I had to prepare the docker image elsewhere, to push it to our own docker hub, and to comment the docker image creation in the ansible playbook.

- The tests are requiring “pbench [to be] installed and configured on all hosts”. This requires to install a new repo. And this was made difficult because our nodes don’t have access to Internet and the repositories to add are not the “standard” rhel-7 ones that we are already mirroring on our Artifactory (which is the only source of rpm which is accessible from our nodes)
- The “Patch pbench-uperf” task (here: https://github.com/openshift/svt/blob/master/networking/synthetic/pod-ip-test-setup.yaml#L93) was failing. I looked at the file to be patched and couldn’t find something similar to the hunks of the patch, so, I tried to just skip that task.  When the “Run pbench-uperf for TCP benchmarks” task was finally launched, it never ended. I looked on the master where the “pbench-uperf” was launched and it appeared that it tried to contact IPs on the overlay network.    The command that was launched was “    python network-test.py podIP --master <master-hostname> --node <node1-hostname> <node2-hostname> --pods 8    ” in order to do the measure between two PODs, but it seems that even this scenario requires the master to be able to reach the overlay network.    This was unfortunately not the case on our current R-Box setup where the masters are not non-schedulable nodes yet.

@vikaschoudhary16 @sjug

**Comment by mffiedler** [comment]
small note: the pench patch was recently removed in PR #100

**Comment by vikaschoudhary16** [comment]
> uperf is automatically packaged inside docker images by the ansible playbook

Not sure about the exact steps but will give it a try to see if it is possible to create a container for running uperf without using internet using just rpms and tools such as busybox.

>  The tests are requiring “pbench [to be] installed and configured on all hosts”. 

As per our internal [ pbench documentation ](http://pbench.perf.lab.eng.bos.redhat.com/agent/installation.html) , external repo has to be installed for installing pbench-agent. Not sure if we should raise a issue on pbench repo for this.

Will get back on third point.

**Comment by vikaschoudhary16** [comment]
> When the “Run pbench-uperf for TCP benchmarks” task was finally launched, it never ended. I looked on the master where the “pbench-uperf” was launched and it appeared that it tried to contact IPs on the overlay network. The command that was launched was “ python network-test.py podIP --master --node --pods 8 ” in order to do the measure between two PODs, but it seems that even this scenario requires the master to be able to reach the overlay network. This was unfortunately not the case on our current R-Box setup where the masters are not non-schedulable nodes yet.

It is not mandatory to launch pbench-uperf on master. If one wants two launch sender and receiver instances of uperf on openshift nodes only, following is the format:
``# python network-test.py podIP --master <master_hostname> --node <node1_hostname> <node2_hostname>--pods <no. of pod-pairs>``

node1 will become sender and node2 will become receiver.

**Comment by vikaschoudhary16** [comment]
partially addressed by #121

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
