### ISSUE TITLE
Networking tests loopback gets stuck trying to register pbench on nodes

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#12]
From old repo:

vikaslaad commented 22 days ago
In the networking tests there is a bug when loopback is run we need to comment 3 lines in inventory file for registering pbench task. Somehow that if condition is not working when node names are not passed.
@ofthecurerh
 
ofthecurerh commented 16 days ago
@vikaslaad could you provide more detail on how you're using it.

There are a few known issues that I and @schituku have run into that I'm working on a PR for. I'll turn these into actual issues to document what is being worked on.

**Comment by vikaslaad** [comment]
I fixed this issue, sorry forgot to close the issue.
