### ISSUE TITLE
Can we control Jmeter's components through Beanshell? I want to disable all assertions through one flag. how can I do it?

### ISSUE THREAD

**Issue by skjadhav282** [openshift/svt#151]

**Comment by mffiedler** [comment]
Not sure how this relates to the OpenShift SVT repo.   Do you have a scenario for using the traffic generation capability of cluster-loader which is not met today?

/cc: @sjug @jmencak

**Comment by sjug** [comment]
It seems @skjadhav282 is using Jmeter which may have more to do with the actual CentOS-stress container image.

We're not using beanshell nor beanshell assertions in Jmeter. I'm not familiar with any command line flags to disable all beanshell assertions in this way.

**Comment by skjadhav282** [comment]
Thanks for all the replies. But finally I have solved this issue by using beanshell.
