### ISSUE TITLE
cluster-loader.py fails when no eth0

### ISSUE THREAD

**Issue by garethahealy** [openshift/svt#175]
The script expects there to be a eth0 interface, but this isnt always the case, a specially with > RHEL7

- https://github.com/openshift/svt/blob/master/openshift_scalability/utils.py#L59

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
