### ISSUE TITLE
cluster-loader.py expects only 1 router

### ISSUE THREAD

**Issue by garethahealy** [openshift/svt#176]
The script only expects 1 router to be deployed, which if there is more than one, causes an error.

- https://github.com/openshift/svt/blob/master/openshift_scalability/utils.py#L60-L61

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary:  https://github.com/openshift/origin/tree/master/test/extended/cluster
