### ISSUE TITLE
cluster-loader autogen option has assumptions that may not work off-cluster

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#196]
I am trying to run cluster-loader -af on a system that is not part of the cluster (my laptop) as a non-root user.  I'm finding that cluster-loader has some hardcoding that makes this difficult/impossible.   This is a scenario we have to support for environments like OpenShift Online where the test will be run remote from the cluster master/nodes.

1.  Assumes it can oc rsync the local /root/.ssh.   rsync-ing the full .ssh dir seems like a very bad idea.  Better is probably provide some way to mount a public key as a secret like the networking tests do.

2. Assumes the local system has an eth0 for "ip addr show eth0"

3. For the scp of results back to the GUN host to work, the GUN host  (obviously) has to be on an IP that is routable/reachable from the pod network.   Running on a laptop inside a VPN will not work.   Best practice is to use a jump node on the same network (same VPC in the case of AWS).

4. Having issues with the seLinuxOptions for the stress pod.  If I remove it, I get permission denied on the oc rsync of .ssh.   When I use the current values I hit the problem that  PR #191 tried to address but that is not the solution.   Need a more reliable means for copying results back to the GUN host.

I will add more as I work through this.  Not sure if it is worth fixing now or wait for upstream

**Comment by jeremyeder** [comment]
Can we possibly agree that the python cluster-loader is frozen as of OCP 3.5?  3.6+ goes with golang version, meaning things like this valid request go to origin/golang only?

**Comment by sjug** [comment]
1. Yeah the assumption was that it was being run from one of the masters, in that case the `.ssh` is  pretty bare. It was my preference for simplicity's sake.
2. We can match against a different pattern instead.

I'm not sure they're bad assumptions, we're just trying to use the tool for things that it wasn't designed for.

**Comment by mffiedler** [comment]
Not pushing for fixes, mainly documenting at this point.  As for considering it frozen, fine within the bounds of practicality.    I'm not up on what the plans are for traffic generation in the golang version.

**Comment by sjug** [comment]
Looking ahead it would be good to know what we like and dislike about the current implementation so it can be improved for the golang version. Did you mean inline docs or a standalone README type document?

**Comment by mffiedler** [comment]
Document for myself in this issue first.   Let me run through this exercise and see where I end up.

**Comment by jmencak** [comment]
Adding a link to https://github.com/openshift/svt/issues/208, which presumably is connected with this?

**Comment by mffiedler** [comment]
Enhancement should be requested in the golang cluster-loader
