### ISSUE TITLE
Need an alternative to placement=test as a node selector for WLG

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#208]
In environments where we do not control node labels (customer, online, etc) we need a different mechanism for node selection for the centos-stress pods.   Maybe just allowing a generic "label_name=value".

/cc: @sjug  @jmencak

**Comment by jmencak** [comment]
For the current WLG, I guess we could just add something like PLACEMENT_KEY env variable, but that would be ugly.  Will keep that in mind for the golang version.
