### ISSUE TITLE
Setup CI for clusterloader

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/svt#235]
During last week's standup, it was discussed that some of the painpoints for clusterloader includes not having a CI.  Following are the high level tasks that are needed to setup CI.

- [ ] Reorganize the existing functions into classes for OpenShift client,
- [ ] Create a proper unit testing framework - that can fake most of client's functionality.
- [ ] Integrate Travis CI to run the core functionality using fakeclient.

**Comment by sjug** [comment]
When was this exactly and what was the discussion?

**Comment by ravisantoshgudimetla** [comment]
Probably it was during retrospective, we had this discussion and the gist of it is

 "After adding new code to clusterloader it needs to be run manually before getting merged. When I asked if we could use CI for that, you told its not there yet" etc.

**Comment by sjug** [comment]
I thought you said it was during stand up?

The last commit other than Jiris shell script fix was over 3 months ago. Nobody is adding new code to cluster loader so that doesn't seem like what was actually said during this discussion you're referring to.

**Comment by ravisantoshgudimetla** [comment]
Right, I am not sure if it was during standup or retrospective, so I used "probably"

So, if you think  we won't be adding too much of code to this deprecated tool, I don't mind closing this issue.

**Comment by ravisantoshgudimetla** [comment]
Closing this as the tool itself is being deprecated.
