### ISSUE TITLE
[STAC] - jq dependency failure.

### ISSUE THREAD

**Issue by mrsiano** [openshift/svt#271]
the following script ./stac-build-n-deploy.sh failed due to:
./stac-build-n-deploy.sh: line 10: jq: command not found
+ registry_svc_ip=
...
Error response from daemon: Get https://:5000/v1/users/: dial tcp :5000: getsockopt: connection refused

we should install issue `yum install jq` in order to solve it.
better to have it via ansible, as part of the following issue https://github.com/openshift/svt/issues/269

@jeremyeder @vikaschoudhary16

**Comment by jeremyeder** [comment]
do we actually ship jq in rhel?  or will it come from another repo?

**Comment by mrsiano** [comment]
right I just figure out it's installed from epel.

**Comment by mrsiano** [comment]
we can have something like this 
oc get svc docker-registry -n default -o json |grep clusterIP |awk '{print $2}' |tr -d '"\,'
and avoid using jq

@jeremyeder @vikaschoudhary16
