### ISSUE TITLE
[STAC] - passwordless communication between pods 

### ISSUE THREAD

**Issue by mrsiano** [openshift/svt#273]
The issue is, we can't ssh from container to docker host.

when executing the stac networking test (https://github.com/openshift/svt/blob/master/networking/synthetic/run-stac-test.sh), it is always ask for ssh psswd.
since we have some sort of iterations it is not ideal for execution.
we need to include the ssh-key inside the container to avoid any ssh authentication dialog during the test execution.

I tried few different methods:
- edit the dockerfile and redeploy the application from scratch within the docker host '.ssh' folder -  it works when I test it with some fedora container, but for our s2i it doesn't.
- I tired to copy keys online manually from the container - didn't work.

please advise 
@sjug @vikaschoudhary16 @jeremyeder

**Comment by jeremyeder** [comment]
I understand what you're saying but I don't see any ssh commands in run-stac-test.sh.  

Is this the command that's not happening:

**Comment by mrsiano** [comment]
hmmm, it's used by stac-build-n-deploy.sh
but yet, it is not working, we need to debug it.
also the run-stac-test.sh dose not execute ssh commands but calls other script inside the container such as runTest.sh, run_common.sh and others.

**Comment by vikaschoudhary16** [comment]
@mrsiano just enable passwordless ssh between the hosts 730-01 and 730-02, then it should work. As pointed by Jeremy, changes are there to mount ssh files to containers, problem is that host ssh files are not updated for passwordless ssh.

**Comment by mrsiano** [comment]
Issue resolved by ssh-copy-id <node>. from each other.

we should automate it, as part of the prepare nodes script.

**Comment by sjug** [comment]
@mrsiano The ssh keys are mounted into the pod, you don't need to `ssh-copy-id` as @vikaschoudhary16 has already explained...

**Comment by mrsiano** [comment]
@sjug  @vikaschoudhary16 right, but it works for me only when the entries of the hosts was placed there, we should consider to have an automation for that thing, may be in part of the prepare-nodes script.

cause authorized_keys file must include the relevant entries, in our case, 70.70.70.x and the actual host name.
and for now we add them manually.

it didn't work unless copying the keys each other (bare-metal).
