### ISSUE TITLE
[STAC] - test failure due to firewall.

### ISSUE THREAD

**Issue by mrsiano** [openshift/svt#281]
when running the stac tests, we faced some firewall issues, the consumer and producer pods can't talk each other, which caused the test to fail.

seems like we need to add some firewall role to ansible "prepare-nodes" script to allow the relevant udp test ports (59935).
or disable iptables completely.

currently, I just disable the iptables on the nodes

@vikaschoudhary16 @jeremyeder

**Comment by vikaschoudhary16** [comment]
I doubt this because i dont remember i ever had to touch iptable explicitly.

**Comment by mrsiano** [comment]
it needs another review, in order to make sure if it needs iptables adaptation
