### ISSUE TITLE
The image server disk is full !

### ISSUE THREAD

**Issue by mbruzek** [openshift/svt#304]
The internal image server disk filled up earlier this week (`df` reported the 1.8T disk was 100% used). The image server contains two directories where the images are stored the `rhel` directory currently has 19 30GB image files, while the `atomic` directory has 26 30GB image files. We deleted the oldest images in each directory but we need to come up with an automated way to ensure that never happens again. 

I had a discussion with @chaitanyaenr about how to resolve this. We discussed several options and decided to create an issue to have a broader discussion about the best way to solve this.

## Use a cron job
The first thought was to create a cron job to run a cleanup script on regular intervals.

## Delete n images before Creating n images
The second option was to delete an image(s) before creating new ones. If for example the script that creates images is going to create 2 images, then delete 2 of the oldest images to ensure the disk size stays even.

## Jenkins cleanup job
The third option we discussed was to create a separate Jenkins job to run a cleanup script on regular intervals. 

Please post to this issue how you would solve the problem and we can discuss the pros and cons of each approach.

**Comment by mbruzek** [comment]
In my experience disconnected tasks such as cron or in this case a Jenkins cleanup job are less than ideal for the following reasons: 
1. The time interval is too short and runs too often. If the images are deleted faster than we create them (such as a failing test blocks the build) the system could delete all the images before we figure out the problem.
2. We will eventually forget to configure or update the task. When we make changes to how many images we create or how frequently they are done the disconnected clean up task is forgotten or neglected and does not keep up with the changes.
3. A task does not get put in source control. Often these tasks are configured outside the repository directory and are specific to the server or Jenkins server it is put on, so they don't get put in source control where we can iterate on the logic when they are not working correctly.
4. The the time interval is too long and the disk fills up again. Say the interval at which the images are created is increased, the old images can grow faster than the job deletes them and we are back in the same problem.

My opinion is that the deletion of n images before creating n images is the best option. This does not rely on timing and if part of the same process, it has a better chance of being updated when/if the image creation code is changed.

**Comment by chaitanyaenr** [comment]
@mbruzek I think we should stick with either creating a cron job or a jenkins job to do the image clean up. The second option requires changing the image provisioner code when actually not needed. We use the same set of playbooks for both ami's and qcow images, we wouldn't want to use the second method for cleaning up ami's.

**Comment by jeremyeder** [comment]
@chaitanyaenr -- I think I agree with @mbruzek points.  The image provisioner ansible itself can handle rotation of images based on free space.

As far as pruning AMIs, that makes sense too.  But we need to sync with the rest of the team about what makes sense there.  So defer that for now, and handle that separately.
