### ISSUE TITLE
Change the name of the images 

### ISSUE THREAD

**Issue by mbruzek** [openshift/svt#333]
Pull https://github.com/openshift/svt/pull/327 will name images differently based on the type. I agree we need to name the images differently.

If I understand correctly change #327 will name images:
```
2017-11-01-ocp-3.7.0-0.189.0-gold.qcow2          #For atomic images
2017-11-01-ocp-3.7.0-0.189.0-rhel-gold.qcow2     #For rhel images
```
The image names need to be consistent and not rely on convention to identify them.

Either way changing the image names will impact the scale-ci work significantly. Once the change is implemented please create an issue at this repo: https://github.com/mbruzek/ansible-openstack-setup/issues to handle the new image names.

**Comment by chaitanyaenr** [comment]
@mbruzek #327 will name the images with the following tags:
2017-11-01-ocp-3.7.0-0.189.0-atomic-gold.qcow2          #For atomic images
2017-11-01-ocp-3.7.0-0.189.0-rhel-gold.qcow2              #For rhel images

**Comment by mbruzek** [comment]
@chaitanyaenr open an issue in github to track the reason for this name change.

**Comment by chaitanyaenr** [comment]
@mbruzek sure, I have opened an issue in ansible-openstack-setup repository.

**Comment by mbruzek** [comment]
Closing this issue and tracking with https://github.com/mbruzek/ansible-openstack-setup/issues/7
