### ISSUE TITLE
Add support for using an existing namespace

### ISSUE THREAD

**Issue by rflorenc** [openshift/svt#36]
cluster-loader.py creates clusterproject{0..N} by default. 
It would be very useful to have it use an existing project namespace (i.e.: logging / metrics) or a set of projects by default.

@hroyrh

**Comment by rflorenc** [comment]
@timothysc PR #46

**Comment by hroyrh** [comment]
I have sent the PR to fix this issue. Refer - [PR #50](https://github.com/openshift/svt/pull/50) 
@timothysc

**Comment by jeremyeder** [comment]
I think this can be closed in favor of #50

**Comment by mffiedler** [comment]
@rflorenc Ricardo, If there are any changes for this PR above and beyond what @hroyrh did in #50, please submit as a new PR.
