### ISSUE TITLE
Image_provisioner: os-kickstart is failing because of python-docutils dependency needed for python-boto

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift/svt#383]

**Comment by mffiedler** [comment]
It's missing from the mirror.  @wabouhamad is in contact with release engineering on the issue and has a workaround.

**Comment by wabouhamad** [comment]
Tracking issue in Jira card:
https://projects.engineering.redhat.com/browse/RCM-26452
The python-docutils pkg should be now in RHEL High Availability and Resilient Storage, I emailed the contacts on that card to obtain the URLs for the repos we need to add to access it

**Comment by chaitanyaenr** [comment]
@wabouhamad thanks for resolving the issue.
