### ISSUE TITLE
Dedicated image for each container

### ISSUE THREAD

**Issue by psuriset** [openshift/svt#385]
In the real world, most containers are instantiated from a dedicated image, so user running 500 pods are likely to have at least 500 unique images, 5000 pods and this scales to at least 5000 images, and so on.
If our scaling tests are instantiating 5000 pods from a single image then we're not getting a representative inventory size. This is a use case for manageiq scale.

**Comment by psuriset** [comment]
@hroyrh @nikhita

**Comment by jhutar** [comment]
I thought we can "workaround" with pushing 1000 images into OpenShift registry and then having something like this in the config file for `./cluster-loader.py`:

```
    pods:
      - total: 1000
      - num: 1
        image: myproject/image1:latest
        basename: image1pod
        file: default
        storage:
          - type: none
      ...
      - num: 1
        image: myproject/image1000:latest
        basename: image1000pod
        file: default
        storage:
          - type: none
```

but I was unsuccessful. To test the approach, I have installed mini OpenShift [1] on my laptop with Fedora 27. then I have built a container, tagged and successfully pushed:

```
# cat Dockerfile 
FROM fedora
MAINTAINER Jan Hutar <jhutar@redhat.com>
# docker build --tag jhutarfedora .
# docker tag jhutarfedora 172.30.1.1:5000/myproject/jhutarfedora
# docker push 172.30.1.1:5000/myproject/jhutarfedora
```

Then created this config and ran the tool:

```
---
projects:
  - num: 1
    basename: jhutarproject
    ifexists: delete
    tuning: default
    quotas: default
    pods:
      - total: 1
      - num: 100
        image: myproject/jhutarfedora:latest
        basename: jhutarpod
        file: default
        storage:
          - type: none

tuningsets:
  - name: default
    pods:
      stepping:
        stepsize: 5
        pause: 10 s
...
# ./cluster-loader.py -f sample-config.yaml
```

It ran successfully, but inspecting containers after the test showed that the pods are using `docker.io/openshift/hello-openshift` images:

```
# docker ps
CONTAINER ID        IMAGE                                                                                                                COMMAND                  CREATED             STATUS              PORTS               NAMES
7c9d94593622        docker.io/openshift/hello-openshift@sha256:7ce9d7b0c83a3abef41e0db590c5aa39fb05793315c60fd907f2c609997caf11          "/hello-openshift"       18 seconds ago      Up 17 seconds                           k8s_hello-openshift_jhutarpod0_jhutarproject0_ee00710c-1659-11e8-bcae-54e1ad81c437_0
c1ce6b28bf1c        openshift/origin-pod:v3.9.0-alpha.3                                                                                  "/usr/bin/pod"           19 seconds ago      Up 18 seconds                           k8s_POD_jhutarpod0_jhutarproject0_ee00710c-1659-11e8-bcae-54e1ad81c437_0
```

I was unable to convince `./cluster-loader.py` to use mine images.

[1] https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container

**Comment by jeremyeder** [comment]
@sjug @mffiedler

**Comment by mffiedler** [comment]
I don't think image: was ever fully implemented for pods:   - I will have to investigate.

To use your image, go to openshift_scalability/content and make a copy of pod-default.json or pod-pause.json and edit it to use your image.   Then update the file: value in your cluster_loader config to use that file.   See config/nodeVertical.yaml for an example.

**Comment by jhutar** [comment]
I would use directly `oc` as a workaround before this gets fixed - you can do something like this to create 10 pods each using different image:

To determine what is the registry URL in your Openstack:

```
$ oc login -u system:admin
$ oc get svc docker-registry
NAME              TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
docker-registry   ClusterIP   172.30.1.1   <none>        5000/TCP   55m
```

Now get token to login to the registry and create a project you will use to create your containers (or create more projects, depending what layout you want - all pods in one project? or one pod per project? ... might need some more for loop:

```
$ oc login -u developer -p developer
$ oc whoami -t   # note the token it prints somewhere
$ oc new-project project-001 --display-name="Testing project 001" --description="Just some project 001"
```

Now push images we will use to start containers:

```
# docker login -u developer -p <the_token_from_above> 172.30.1.1:5000
# cat Dockerfile
FROM fedora
MAINTAINER Foo Bar <foobar@example.com>
CMD [ "/usr/bin/sleep", "999" ]
# for i in $( seq -w 10); do echo "########## $i ##########"; cp Dockerfile Dockerfile-$i; echo "RUN echo '$i' >/myid.txt" >>Dockerfile-$i; docker build --tag testing-$i - <Dockerfile-$i; docker tag testing-$i 172.30.1.1:5000/project-001/testing-$i:latest; docker push 172.30.1.1:5000/project-001/testing-$i:latest; done
```

Now start the containers:

```
$ for i in $( seq -w 10 ); do oc new-app --image-stream project-001/testing-$i:latest --name testing-$i-deployment; done
```

And to cleanup your env:

```
$ oc delete project/project-001
```

**Comment by jhutar** [comment]
Found these resources useful:

 * hello-openshift container: https://github.com/openshift/origin/tree/master/examples/hello-openshift
 * accessing registry on mini setup: https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#accessing-the-openshift-registry-directly
 * blog about cluster-loader: https://blog.openshift.com/managing-the-lifecycle-of-openshift-clusters-vetting-openshift-installations/
 * configuring "insecure-registry": https://docs.openshift.org/latest/getting_started/administrators.html#try-it-out
