### ISSUE TITLE
setup_pbench_pods.sh doesn't create pbench-agent pods in pbench namespace

### ISSUE THREAD

**Issue by jmencak** [openshift/svt#424]
https://github.com/openshift/svt/blob/master/openshift_tooling/pbench/setup_pbench_pods.sh#L87

@chaitanyaenr , PTAL

**Comment by jmencak** [comment]
Yes, default namespace.

**Comment by chaitanyaenr** [comment]
@jmencak just checking to see if I got it right, the pbench pods are up and running but in the default namespace instead of pbench right?

**Comment by jmencak** [comment]
Yes, pbench pods are up and running but in the default namespace instead of pbench namespace.
