### ISSUE TITLE
Image provisioner compatibility will be broken with changes for 3.10

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#432]
With the architectural changes for  3.10 the image provisioner will break backwards compatibility with 3.9 and earlier.  Until now, we were able to roughly keep things compatible.   Some things like supported docker levels are likely broken for really old (3.2, 3.3, etc) releases but being able to generate gold images for n-1, n-2 releases is sufficient.

I propose creating a "pre-3.10" branch of the svt repo to preserve a version of the provisioner (and possibly tests) that would be broken by 3.10 changes.   Comments?

See PR #430 for an example

**Comment by jeremyeder** [comment]
@openshift/svt

**Comment by chaitanyaenr** [comment]
@mffiedler creating a pre-3.10 branch makes sense to me. It would be nice if we can do the same with aos-ansible since there have been few architectural changes in 3.10 which broke our image builds.

**Comment by mffiedler** [comment]
I'm seeing other tools like svt/conformance that will require pre-3.10 as well.   Runtime version checking is another possibility.  I've optimistically created the branch and am inclined to merge #430 unless I hear objections.

**Comment by sjug** [comment]
I like the runtime checking more than a branch.

**Comment by mffiedler** [comment]
PR #430 merged
