### ISSUE TITLE
update start-network-test.sh permutations to reduce time-to-run

### ISSUE THREAD

**Issue by jeremyeder** [openshift/svt#448]
https://github.com/openshift/svt/blob/master/networking/synthetic/start-network-test.sh

This takes ~19 hours to run.  Seems excessive and is not really CI friendly nor do I believe the extra testing is providing value worth that amount of time.

I suggest we adjust the following from the default scenario coverage:

* Change ```1 2 4 8``` to ```1 2 $(nprocs)``` on line 44.
* Remove scenarios on lines 47,52,57,62.
* Change all sleeps to 60 seconds.

@schituku @chaitanyaenr

**Comment by mffiedler** [comment]
Would prefer to add a parameter whether the test is full or CI.
