### ISSUE TITLE
Networking test is clearing pbench tools on the cluster

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift/svt#519]
The node-ip-setup, pod-ip-setup and svc-ip-setup playbooks are clearing tools on the cluster. This isl causing problems on scale ci environment as we just register the tools once before starting the tests and use the same set of tools for all the tests.

**Comment by schituku** [comment]
I will take care of this in the PR I'm working on for the INT mode changes.

**Comment by chaitanyaenr** [comment]
#528 fixed the issue.
