### ISSUE TITLE
Git test script incorrectly outputs start time instead of elapsed time

### ISSUE THREAD

**Issue by JohnStrunk** [openshift/svt#526]
echo-ed variable should be `${rm_time}` instead of `${rm_start_time}`

https://github.com/openshift/svt/blob/e402134e5400453a112154c420b1d2be8eef44a0/storage/git/files/scripts/test-git.sh#L54

@hongkailiu

**Comment by hongkailiu** [comment]
Thanks, @JohnStrunk 
Created https://github.com/openshift/svt/pull/527
