### ISSUE TITLE
Create 3.11 branch for svt

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift/svt#538]
We need to make some changes for the tooling to work on next OCP version, I think we should create a 3.11 branch to save the state.

**Comment by chaitanyaenr** [comment]
@mffiedler PTAL.

**Comment by mffiedler** [comment]
svt-3.11 created.   /cc: @wabouhamad

**Comment by chaitanyaenr** [comment]
Thanks @mffiedler.
