### ISSUE TITLE
Rename Alderaan pipeline

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift/svt#568]
Alderaan pipeline was named to reflect the automation around installation, configuration and running scale tests on OCP running on top of OSP ( Alderaan machines in scale lab ).  The pipeline has the support to run the scale tests on public clouds including AWS, Azure.  @ashishkamra @akrzos and I have been discussing about renaming it to something else to reflect that it supports multiple cloud providers and is flexible enough to on board new workloads.

We can name it gears if we want to get creative or just scalability pipeline . Please feel free to recommend any other names. 

@jeremyeder @akrzos @ashishkamra @sjug @mffiedler @wabouhamad @jmencak  @ekuric @Deepthidharwar  @zvonkok @ahardin-rh

**Comment by jmencak** [comment]
With all the changes everywhere else, do we really have to rename it? :) If so, the not-so-creative `scalability/scale-ci` is good enough for me.

**Comment by mffiedler** [comment]
Since Alderaan was destroyed in a horrific manner with millions of voices crying out in terror, I +1 the rename.    :-)

**Comment by ashishkamra** [comment]
+1 to scale-ci. Or just scalability as suggested by Ravi in case we don't think CI is the focus of this pipeline anymore.

**Comment by jeremyeder** [comment]
you guys are boring! :cry:

**Comment by ahardin-rh** [comment]
cloud-scaler? :cloud: :bridge_at_night:  I'm trying to think of something creative, but failing hard. :thinking:

**Comment by ashishkamra** [comment]
hybrid-cloud-scaler ?

**Comment by mffiedler** [comment]
hybrid-cloud-scaler.next

**Comment by akrzos** [comment]
Some other names
* Scalability Pipeline - SP
* Container Scale Pipeline - CSP
* Open Container Scale Pipeline - OCSP
* Shift Scale Pipeline - SSP
* Polynimbus Scalability Pipeline - PSP

**Comment by jeremyeder** [comment]
I can't resist.

I nominate purely "CI". Which stands for Cache Invalidation, one of the hardest problems in Computer Science.  CI now has two meanings, which means it's not boring and FUN.

https://martinfowler.com/bliki/TwoHardThings.html

**Comment by chaitanyaenr** [comment]
cogwheel?

**Comment by smalleni** [comment]
I suggest clockwork :-)

**Comment by akrzos** [comment]
I have a few others:

- Cluster Cruncher
- Cloud Crunch
- Shift Stress
- Shift Gauge
- Kube Gauge

**Comment by akrzos** [comment]
No thoughts from anyone else?  Any votes? Any other star wars references maybe?  I am partial to Cluster Cruncher at this point. Otherwise I think we should maintain it as simply scale-ci to avoid further confusion.

**Comment by chaitanyaenr** [comment]
scale-ci pipeline controls the workflow of multiple Jobs and is pluggable, so I  think cogwheel would be a good name to reflect that.

**Comment by jmencak** [comment]
Cluster Cruncher sounds cool, sorry Ravi, Cogwheel ain't that cool. ;)

**Comment by wabouhamad** [comment]
Cluster Torture (CT)

**Comment by wabouhamad** [comment]
Cluster Tormentor

**Comment by smalleni** [comment]
Cluster Buster

**Comment by sjug** [comment]
> Cluster Buster

My favorite so far.

LoNDN - Lots of Nodes Doing Nothing
