### ISSUE TITLE
Evaluate current test run parameters

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#58]
Now that there is 2 releases worth of data, experience and lessons-learned using cluster-loader for vertical and horizontal testing, we should update/modify the tests as appropriate.   Possible areas:
- project composition
- new scale targets from online, if available
- tradeoffs between test execution time and success - don't overwhelm the cluster.
- template contents
- other?

cc: @timothysc @jeremyeder

**Comment by timothysc** [comment]
- There are a bunch of new objects to account for.  
- Adding jitter. 
- More bulk per operation for larger deployments.

**Comment by mffiedler** [comment]
Test run parameters have been adjusted appropriately over the course of OpenShift releases.
