### ISSUE TITLE
Update reliability README once new feature set stabilizes

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#672]
The README will require updates, but let's wait until the first set of new features stabilizes - until custom operations are available at a minimum.

**Comment by qiliRedHat** [comment]
Working on this in https://github.com/openshift/svt/pull/677

**Comment by qiliRedHat** [comment]
https://github.com/openshift/svt/pull/677 is done and merged. Close this.

**Comment by mffiedler** [comment]
Reliability V2 README is in good shape
