### ISSUE TITLE
Reliability:  make log location configurable, default to /tmp/reliability.log

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#673]
log location is hardcoded today which prevents running 2 reliability tests from the same jump host unless you modify the location in the code.   This should be configurable and default to the current location

**Comment by qiliRedHat** [comment]
Working on this in #677

**Comment by qiliRedHat** [comment]
https://github.com/openshift/svt/pull/677 is done and merged. Close this.

**Comment by mffiedler** [comment]
Fixed by #677
