### ISSUE TITLE
Reliability: Logging Options

### ISSUE THREAD

**Issue by paigerube14** [openshift/svt#678]
It would be nice to be able to set how much output we want to see in the logs. When the reliability test is running for a long time, just looking at the terminal it is hard to see if there are any issues and what is going on 

For example, on line https://github.com/qiliRedHat/svt/blob/92c4e7a519c3651ab741ef0dca4f6117169aca5e/reliability/tasks/utils/oc.py#L16 prints the output of every command we execute. Would be nice to only print or have the option to only print this output when rc != 0.
When doing the monitor cluster operators, it is a lot of extra output that is not useful if all operators are healthy. If the operator is degraded we are already printing an error https://github.com/qiliRedHat/svt/blob/92c4e7a519c3651ab741ef0dca4f6117169aca5e/reliability/tasks/Monitor.py#L22

@qiliRedHat, possible improvement for the future 

I'm not sure exactly how this would be done, any thoughts?

**Comment by qiliRedHat** [comment]
@paigerube14 Thank you! This is a good suggestion! 
The monitor cluster operators is a good example to do this. While there may be some case that `oc command rc==0` !=`result of the oc command is healthy`. I need to go through the code to check this and add assertion if needed. And your enhancement request inspired me that for customized task, we can allow user to add some assertion too.

**Comment by qiliRedHat** [comment]
1. https://github.com/openshift/svt/pull/700 includes the enhancement to address this issue. Added ignore_log flag to enable or disable command output written to log file.
2. As now we have slack integration, I suggest using slack channel- which only output hight info and error command notifications. It's more convenience to get noticed or check for errors than checking in log file.
3. Check 'all operators' function is changed NOT to output the whole yaml now.

**Comment by qiliRedHat** [comment]
@paigerube14 Shall we close this issue? I got a stale notification.
