### ISSUE TITLE
masterVertical.sh and pyconfigMasterVirtScale.yaml behaviour

### ISSUE THREAD

**Issue by jmencak** [openshift/svt#69]
@timothysc 
I've run ./masterVertical.sh in svt and got this:

<pre>
In project clusterproject3 on server https://ip-172-31-41-250.us-west-2.compute.internal:8443

route/route0 not accepted: HostAlreadyClaimed (svc/service0)
  dc/deploymentconfig0 deploys docker.io/openshift/hello-openshift:latest 
    deployment #1 deployed about an hour ago - 1 pod

route/route1 not accepted: HostAlreadyClaimed (svc/service1)
  dc/deploymentconfig1 deploys docker.io/openshift/hello-openshift:latest 
    deployment #1 deployed about an hour ago - 1 pod

svc/service2v0 - 172.30.252.181:80 -> 8080
  dc/deploymentconfig2v0 deploys docker.io/openshift/hello-openshift:latest 
    deployment #1 deployed about an hour ago - 2 pods

bc/buildconfig0 source builds git://github.com/tiwillia/hello-openshift-example.git on istag/imagestream0:latest (from bc/buildconfig0)
  -> istag/imagestream0:latest
  build #1 failed 59 minutes ago

bc/buildconfig1 source builds git://github.com/tiwillia/hello-openshift-example.git on istag/imagestream1:latest (from bc/buildconfig1)
  -> istag/imagestream1:latest
  build/build1-1 failed about an hour ago (can't push to image)

bc/buildconfig2 source builds git://github.com/tiwillia/hello-openshift-example.git on istag/imagestream2:latest (from bc/buildconfig2)
  -> istag/imagestream2:latest
  build/build2-1 failed about an hour ago (can't push to image)

Errors:
  * bc/buildconfig1 is pushing to istag/imagestream1:latest, but the image stream for that tag does not exist.
  * bc/buildconfig2 is pushing to istag/imagestream2:latest, but the image stream for that tag does not exist.
  * build/build1-1 has failed.
  * build/build2-1 has failed.
  * route/route0 was not accepted by router "router": a route in another namespace holds www.example0.com and is older than route0 (HostAlreadyClaimed)
  * route/route1 was not accepted by router "router": a route in another namespace holds www.example1.com and is older than route1 (HostAlreadyClaimed)
  * route/route2 was not accepted by router "router": a route in another namespace holds www.example2.com and is older than route2 (HostAlreadyClaimed)

7 errors and 6 warnings identified, use 'oc status -v' to see details.
</pre>

Tested on two clusters, same results.  Not sure this is the intended behaviour.

**Comment by timothysc** [comment]
We should probably revisit the * on master-virt.  I do recall there being issues with the image stream but at the time we were more concerned with filling resources on the master then proper behavior.  

The route issue is not something I've seen before.

**Comment by mffiedler** [comment]
@jmencak I should have looked at the exact errors more closely.   These are all expected.   The builds and routes are there to "take up space/resources" in etcd and in the master.   They are not expected to be operational.   The only things that are up-and-running after running the script are 4 hello-openshift pods per project.   The secrets, builds, build configs, imagestreamtags, etc, etc are there to push the control plane - not to be operational runtime artifacts.

I will open and issue to document this better in that yaml file.   Too many people have wasted time debugging those failed builds

**Comment by jmencak** [comment]
@mffiedler Thanks, much appreciated.  I actually assumed that might be the case, that's why I've asked in the first place if that was the expected behaviour.  In a way it is "documented" in "./content/build-template.json" -- "This template will create a single (failed) build." Thanks!

**Comment by mffiedler** [comment]
Re-purposing this issue to provide some less subtle documentation on the intended behavior of this yaml file per the comments above.

**Comment by xevelzol** [comment]
workaround:

**Comment by mffiedler** [comment]
cluster-loader enhancements should be requested for the golang version in the openshift-tests binary: https://github.com/openshift/origin/tree/master/test/extended/cluster
