### ISSUE TITLE
Use yaml.safe_load() instead of yaml.load()

### ISSUE THREAD

**Issue by paigerube14** [openshift/svt#693]
Got a product security email stating we should be using safe load instead of load. Think there are a couple other files other than the below but will create PR's to update 

https://github.com/openshift/svt/blame/master/openshift_scalability/ci/scripts/get_pod_total.py#L8
https://github.com/openshift/svt/blame/master/openshift_scalability/ci/scripts/get_pod_total.py#L20

**Comment by dbaker-rh** [comment]
Looks good to me!  Thank you.
