### ISSUE TITLE
Docker build issue with Network tests

### ISSUE THREAD

**Issue by vikaslaad** [openshift/svt#86]
Network tests do not work anymore on master node, docker build is failing because of Openshift firewall. Need to make tests run from a separate host.

**Comment by jeremyeder** [comment]
I think this presents a great opportunity to port the network performance tests to the cluster-loader and workload-generator approach.  @sjug any thoughts?

**Comment by sjug** [comment]
Will talk to @vikaslaad to get more details.

**Comment by mffiedler** [comment]
In my testing to get the networking suite fully functional I did not see this issue.    Was it the Docker build task that was failing?    I'm running from the master.   Are there any error messages/logs around from this problem?  

/cc: @vikaslaad @schituku

**Comment by vikaslaad** [comment]
Yes the error was the pbench install step, when it tries to get the pbench repo file. It was not able to talk to outside world. It was failing at following step, I did it on master in new env and its not happening for me anymore.

Step 5 : RUN curl -o /etc/yum.repos.d/pbench.repo https://copr.fedorainfracloud.org/coprs/ndokos/pbench/repo/epel-7/ndokos-pbench-epel-7.repo;     yum clean expire-cache;     yum install --assumeyes            configtools     pbe
nch-agent      pbench-uperf;     yum clean all;     source /etc/profile.d/pbench-agent.sh
 ---> Running in 8774e00bab4c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   318  100   318    0     0    348      0 --:--:-- --:--:-- --:--:--   348

**Comment by mffiedler** [comment]
Could be some difference in the AMIs.    We can reopen this issue if it happens again.
