### ISSUE TITLE
Kitchen Sink: Mark all json templates triggers in quickstarts to automatic: true 

### ISSUE THREAD

**Issue by schituku** [openshift/svt#88]
The automatic: false flag in the triggers of the templates for deployments was not working till 3.4 and hence when the cluster loader creates app as part of the kitchen sink tests rolled out the deployments which are marked as false. Now that it is fixed it is no longer deploying apps automatically and one has to manually deploy the services thru "oc rollout latest" after the cluster loader script finishes. 
     Change all flags to automatic: true so that deployments happen automatically and no manual intervention is needed.

https://github.com/openshift/origin/blob/master/UPGRADE.md#origin-14x--ose-34x

**Comment by jmencak** [comment]
Created a PR https://github.com/openshift/svt/pull/83 some time ago...

**Comment by mffiedler** [comment]
Merged PR #83.   Should have merged earlier.
