### ISSUE TITLE
Add a window-scaling functionality to cluster loader.

### ISSUE THREAD

**Issue by jmencak** [openshift/svt#89]
While the current stepsize/pause/delay options in the tuningsets sections of cluster-loader templates can be useful to rate-limit and mitigate issues like:

    Error syncing pod, skipping: failed to "StartContainer" for "POD"  with RunContainerError: "runContainer: operation timeout: context deadline exceeded"

I've found that just by keeping only a certain number of pods outside of Running state seems to mitigates this issue automatically without estimating the tuningsets values to avoid this issue.

Therefore I propose to add a "queue-depth" field/functionality in the tuningsets section for cluster-loader templates, which would block the creation of new pods if the queue depth is greater than a given number.

Adding a link to a thread:
http://post-office.corp.redhat.com/archives/openshift-sme/2016-November/msg00301.html

@jeremyeder @sjug

**Comment by jeremyeder** [comment]
Currently an open BZ for this feature as well:
https://bugzilla.redhat.com/show_bug.cgi?id=1392980

ETA for that is probably longer term.  We need this feature sooner.  Call it window-scaling.

**Comment by DanyC97** [comment]
any progress on this? I'm running Origin 1.4.1 and i hit the same behavior ...

**Comment by jmencak** [comment]
@sjug, something to consider for the new, golang cluster loader?

**Comment by jeremyeder** [comment]
Yeah, I think this is very useful. We would want to make sure that we constantly log queue depth (every 10s or so).

However just so we are clear...this does not fully replace tuningset, because we still want the steps so that we have data sets at various tiers of load as we ramp up.

**Comment by mffiedler** [comment]
New functionality should be added to golang cluster-loader
