### ISSUE TITLE
Bring network tests up to date with OCP, Ansible, pbench, etc

### ISSUE THREAD

**Issue by mffiedler** [openshift/svt#98]
- Issue #87 - use the Ansible 2.0 API
- remove pbench-uperf patching
- update playbooks for latest OCP template processing syntax
- respect new pbench-uperf port range 
- investigate svc-to-svc problem
- investigate output data issue (possible pbench-uperf bug)
- require user to explicitly provide public ssh key for pods to use
- ??? more to be added as discovered

**Comment by jeremyeder** [comment]
There is a feature we need as well:  in addition to svc-to-svc and pod-to-pod, we also need host-to-host tests as part of this suite.

**Comment by mffiedler** [comment]
Opened issue #99 for node-to-node.  I'll add that as I make these updates.

**Comment by mffiedler** [comment]
Network tests now maintained in ripsaw repo:   cloud-bulldozer/ripsaw on github
